version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: landing-web
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  php-fpm:
    build: .docker/php-fpm
    container_name: landing-php
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
